name: Release

on:
  push:
    branches:
    - main

jobs:
  release:
    name: Semantic Release & Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install git-chglog
      run: |
        GHCHGLOG_VERSION="0.15.4"
        curl -L https://github.com/git-chglog/git-chglog/releases/download/v${GHCHGLOG_VERSION}/git-chglog_${GHCHGLOG_VERSION}_linux_amd64.tar.gz | tar -xz
        chmod +x git-chglog
        sudo mv git-chglog /usr/local/bin/

    - name: Calculate next SemVer version
      id: version
      run: |
        chmod +x .github/scripts/calc-next-version.sh
        bash .github/scripts/calc-next-version.sh

    - name: Generate CHANGELOG
      run: git-chglog -o CHANGELOG.md ${{ env.RELEASE_VERSIONV }}

    - name: Commit CHANGELOG and tag
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add CHANGELOG.md
        git commit -m "docs(changelog): update CHANGELOG for ${{ env.RELEASE_VERSION }}" || echo "No changes to commit"
        git tag -a "${{ env.RELEASE_VERSION }}" -m "Release ${{ env.RELEASE_VERSION }}"
        git push origin main --tags

    - name: Build binaries
      run: |
        mkdir -p dist
        GOOS=linux   GOARCH=amd64 go build -o dist/secrethor-cli-linux   ./main.go
        GOOS=darwin  GOARCH=amd64 go build -o dist/secrethor-cli-darwin  ./main.go
        GOOS=windows GOARCH=amd64 go build -o dist/secrethor-cli.exe     ./main.go
        cd dist && zip secrethor-cli-windows.zip secrethor-cli.exe
        cd dist && tar -czf secrethor-cli-linux.tar.gz secrethor-cli-linux
        cd dist && tar -czf secrethor-cli-darwin.tar.gz secrethor-cli-darwin

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.NEW_VERSION }}
        name: Release ${{ env.NEW_VERSION }}
        body_path: CHANGELOG.md
        files: |
          dist/secrethor-cli-linux.tar.gz
          dist/secrethor-cli-darwin.tar.gz
          dist/secrethor-cli-windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
